version: "3"

services:
  nodeserver:
    build:
      context: ./node
      dockerfile: Dockerfile
    image: nichenevercosa/nodeex:latest
    container_name: nodeex
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s node index.js
    tty: true
    volumes:
      - /usr/src/app/node_modules
    networks:
      - mynet
    ports:
      - "3000:3000"
    depends_on:
      - db

  nginx:
    restart: always
    build:
      context: ./nginx
      dockerfile: Dockerfile
    image: nichenevercosa/nginx:latest
    container_name: nginx
    networks:
      - mynet
    ports:
      - "8080:80"
    depends_on:
      - nodeserver

  db:
    platform: linux/x86_64
    image: mysql:5.7
    command: --innodb-use-native-aio=0
    container_name: db
    restart: always
    tty: true
    volumes:
      - ./mysql:/var/lib/mysql
    environment:
      - MYSQL_DATABASE=nodedb
      - MYSQL_ROOT_PASSWORD=root
    networks:
      - mynet

networks:
  mynet:
    driver: bridge
